dist: xenial
language: go
go:
  - '1.14.x'
cache:
  bundler: true
  directories:
    - $HOME/docker
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
sudo: required
env:
  - HOME=/home/travis
services:
  - docker
go_import_path: volcano.sh/volcano
before_cache:
  # Save tagged docker images
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --filter=reference='volcanosh/example*' --filter=reference='kindest/node*' --filter=reference='k8s.gcr.io/*' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
before_install:
  - |
    if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(\.md)|(\.png)|(\.pdf)|(\.html)|^(LICENSE)|^(docs)|^(OWNERS)|^(MAINTAINERS)'
    then
      echo "Only doc files were updated, skip running the CI."
      travis_terminate 0
    fi
jobs:
  include:
    - stage: Code Verify 
      #Golint & Gofmt
      script:
        - make verify
    - #Verify Deployment Yaml
      script:
        - echo "Verifying contents of installer/development.yaml with generated yaml"
        - make TAG=latest generate-yaml
        - make verify-generated-yaml
    - #UT Tests
      script:
        - make unit-test
    - stage: E2E Tests #E2E Job
      before_script:
        # Download kubectl
        - sudo curl -o /usr/local/bin/kubectl -L https://storage.googleapis.com/kubernetes-release/release/v1.16.6/bin/linux/amd64/kubectl
        - sudo chmod +x /usr/local/bin/kubectl
        # Download kind binary (0.6.1)
        - sudo curl -o /usr/local/bin/kind -L https://github.com/kubernetes-sigs/kind/releases/download/v0.6.1/kind-linux-amd64
        - sudo chmod +x /usr/local/bin/kind
        - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
      script:
        - make vcctl
        - make images
        - make e2e-test-job
    - #E2E Scheduling
      before_script:
        # Download kubectl
        - sudo curl -o /usr/local/bin/kubectl -L https://storage.googleapis.com/kubernetes-release/release/v1.16.6/bin/linux/amd64/kubectl
        - sudo chmod +x /usr/local/bin/kubectl
        # Download kind binary (0.6.1)
        - sudo curl -o /usr/local/bin/kind -L https://github.com/kubernetes-sigs/kind/releases/download/v0.6.1/kind-linux-amd64
        - sudo chmod +x /usr/local/bin/kind
        - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
      script:
        - make vcctl
        - make images
        - make e2e-test-scheduling
    - stage: Publish latest Docker Image on Daily Build
      script:
        - echo "Publish latest Docker Images to DockerHub"
      deploy:
        - provider: script
          script: make TAG=latest RELEASE_VER=latest release
          on:
            condition: $TRAVIS_EVENT_TYPE = cron
notifications:
  webhooks: https://www.travisbuddy.com/
  on_success: never
