apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: jobs.extensions.arbitrator.incubator.k8s.io
spec:
  group: extensions.arbitrator.incubator.k8s.io
  names:
    kind: Job
    plural: jobs
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            minAvailable:
              format: int32
              type: integer
            schedulerName:
              type: string
            taskSpecs:
              items:
                properties:
                  replicas:
                    format: int32
                    type: integer
                  selector:
                    type: object
                  template:
                    type: object
                type: object
              type: array
          type: object
        status:
          properties:
            succeeded:
              format: int32
              type: integer
            failed:
              format: int32
              type: integer
            minAvailable:
              format: int32
              type: integer
            pending:
              format: int32
              type: integer
            running:
              format: int32
              type: integer
          type: object
      type: object
  version: v1alpha1
